CREATE SEQUENCE IF NOT EXISTS config_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS items_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE committee_members
(
    committee VARCHAR(20)           NOT NULL,
    user_id   VARCHAR(64)           NOT NULL,
    is_active BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE config
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active_year        SMALLINT                                NOT NULL,
    is_annadaan_active BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT config_pk PRIMARY KEY (id)
);

CREATE TABLE donations
(
    id             TEXT        NOT NULL,
    type           VARCHAR(20) NOT NULL,
    donor_name     TEXT,
    donor_building VARCHAR(1),
    donor_flat     SMALLINT,
    quantity       SMALLINT DEFAULT 0,
    CONSTRAINT donations_pk PRIMARY KEY (id)
);

CREATE TABLE item_bookings
(
    donation_id TEXT            NOT NULL,
    item_id     BIGINT          NOT NULL,
    quantity    FLOAT DEFAULT 1 NOT NULL,
    amount      FLOAT DEFAULT 0 NOT NULL
);

CREATE TABLE items
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name TEXT                                    NOT NULL,
    type      VARCHAR(20)                             NOT NULL,
    price     FLOAT DEFAULT 1                         NOT NULL,
    quantity  FLOAT DEFAULT 1                         NOT NULL,
    amount    FLOAT DEFAULT 0                         NOT NULL,
    CONSTRAINT item_pk PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id          TEXT        DEFAULT gen_random_uuid() NOT NULL,
    description TEXT,
    amount      FLOAT                                 NOT NULL,
    date        date        DEFAULT CURRENT_DATE      NOT NULL,
    committee   VARCHAR(20)                           NOT NULL,
    year        SMALLINT                              NOT NULL,
    txn_user_id VARCHAR(64)                           NOT NULL,
    txn_type    VARCHAR(20) DEFAULT 'DONATION'        NOT NULL,
    txn_mode    VARCHAR(20) DEFAULT 'ONLINE'          NOT NULL,
    log_user_id VARCHAR(64)                           NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()             NOT NULL,
    linked_id   TEXT,
    CONSTRAINT transactions_pk PRIMARY KEY (id)
);

CREATE TABLE users
(
    clerk_id   VARCHAR(64)                NOT NULL,
    email      TEXT                       NOT NULL,
    first_name TEXT                       NOT NULL,
    last_name  TEXT,
    image_url  TEXT,
    role       VARCHAR(10) DEFAULT 'USER' NOT NULL,
    building   VARCHAR(1)                 NOT NULL,
    flat       SMALLINT                   NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()  NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()  NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (clerk_id)
);

ALTER TABLE items
    ADD CONSTRAINT annadaan_pk_2 UNIQUE (item_name);

ALTER TABLE committee_members
    ADD CONSTRAINT committee_members_pk UNIQUE (committee, user_id);

ALTER TABLE item_bookings
    ADD CONSTRAINT item_bookings_pk UNIQUE (donation_id, item_id);

ALTER TABLE users
    ADD CONSTRAINT users_pk_2 UNIQUE (email);

ALTER TABLE committee_members
    ADD CONSTRAINT committee_members_users_slug_fk FOREIGN KEY (user_id) REFERENCES users (clerk_id) ON DELETE NO ACTION;

ALTER TABLE donations
    ADD CONSTRAINT donations_id_fkey FOREIGN KEY (id) REFERENCES transactions (id) ON DELETE NO ACTION;

ALTER TABLE item_bookings
    ADD CONSTRAINT item_bookings_item_id_fk_2 FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE NO ACTION;

ALTER TABLE item_bookings
    ADD CONSTRAINT item_bookings_txn_id_fk_1 FOREIGN KEY (donation_id) REFERENCES donations (id) ON DELETE NO ACTION;

ALTER TABLE transactions
    ADD CONSTRAINT transactions_txn_fk_3 FOREIGN KEY (linked_id) REFERENCES transactions (id) ON DELETE NO ACTION;

ALTER TABLE transactions
    ADD CONSTRAINT transactions_users_fk_1 FOREIGN KEY (txn_user_id) REFERENCES users (clerk_id) ON DELETE NO ACTION;

ALTER TABLE transactions
    ADD CONSTRAINT transactions_users_fk_2 FOREIGN KEY (log_user_id) REFERENCES users (clerk_id) ON DELETE NO ACTION;