INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('1', 'Aata Aashirwad 10kg', 'ANNADAAN', '410', '10', '4100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('2', 'Ajwain 100 gm', 'ANNADAAN', '40', '1', '40');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('3', 'Anjeer 1kg', 'ANNADAAN', '1300', '5', '6500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('4', 'Ararot', 'ANNADAAN', '50', '4', '200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('5', 'Badam', 'ANNADAAN', '960', '0.5', '480');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('6', 'Baking Powder 50 gm', 'ANNADAAN', '27', '2', '54');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('8', 'Beans', 'ANNADAAN', '80', '2', '160');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('9', 'Beetroot', 'ANNADAAN', '80', '5', '400');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('10', 'Besan', 'ANNADAAN', '115', '4', '460');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('11', 'Bhindi', 'ANNADAAN', '80', '8', '640');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('12', 'Black Pepper 10gm', 'ANNADAAN', '15', '3', '45');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('13', 'Black salt 100gm', 'ANNADAAN', '40', '2', '80');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('14', 'Brinjal', 'ANNADAAN', '80', '8', '640');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('15', 'Butter', 'ANNADAAN', '610', '1', '610');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('16', 'Capsicum', 'ANNADAAN', '120', '5', '600');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('17', 'Carrots', 'ANNADAAN', '80', '12', '960');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('18', 'Cauliflower', 'ANNADAAN', '60', '10', '600');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('19', 'Charoli 200 gm', 'ANNADAAN', '560', '1', '560');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('20', 'Chat Masala 100gm', 'ANNADAAN', '75', '4', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('21', 'Coconut powder', 'ANNADAAN', '270', '1', '270');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('22', 'Coriander bunch', 'ANNADAAN', '20', '15', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('23', 'Cream', 'ANNADAAN', '230', '3', '690');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('24', 'Cucumber', 'ANNADAAN', '60', '18', '1080');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('25', 'Custard Powder', 'ANNADAAN', '75', '2', '150');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('26', 'Dahi', 'ANNADAAN', '90', '15', '1350');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('27', 'Dalchini 10 gm', 'ANNADAAN', '10', '3', '30');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('28', 'Dhana 250 gm', 'ANNADAAN', '50', '1', '50');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('29', 'Dhana Powder', 'ANNADAAN', '340', '1', '340');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('30', 'Disposible Glass 30 pc', 'ANNADAAN', '30', '45', '1350');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('31', 'Disposible Spoon 100 pc', 'ANNADAAN', '40', '20', '800');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('32', 'Duster light', 'ANNADAAN', '25', '12', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('33', 'Elaichi 50 gm', 'ANNADAAN', '180', '1', '180');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('34', 'Elaichi masala 10 gm', 'ANNADAAN', '15', '3', '45');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('35', 'Garlic', 'ANNADAAN', '500', '2', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('36', 'Gas Cylinder', 'ANNADAAN', '0', '4', '0');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('37', 'Gawar', 'ANNADAAN', '80', '5', '400');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('38', 'Gemini Sunflower 15 Ltr', 'ANNADAAN', '2190', '4', '8760');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('39', 'Ghee 1 Ltr', 'ANNADAAN', '720', '4', '2880');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('40', 'Ginger', 'ANNADAAN', '250', '2', '500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('41', 'Goda masala 100gm', 'ANNADAAN', '39', '6', '234');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('42', 'Gul', 'ANNADAAN', '60', '3', '180');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('43', 'Haldi 200gm', 'ANNADAAN', '84', '5', '420');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('44', 'Hing 200gm', 'ANNADAAN', '340', '1', '340');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('45', 'Imli', 'ANNADAAN', '160', '1', '160');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('46', 'Jayfal (Nutmeg)', 'ANNADAAN', '10', '10', '100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('47', 'Jeera 250gm', 'ANNADAAN', '95', '4', '380');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('48', 'Kadipatta', 'ANNADAAN', '10', '1', '10');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('49', 'Kaju tukda', 'ANNADAAN', '340', '3', '1020');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('50', 'Kaju whole', 'ANNADAAN', '920', '1', '920');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('51', 'Karela', 'ANNADAAN', '60', '5', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('52', 'Kasuri Methi 100gm', 'ANNADAAN', '95', '2', '190');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('53', 'Kesar color 10 gm', 'ANNADAAN', '7', '3', '21');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('54', 'Khopra powder', 'ANNADAAN', '200', '1', '200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('55', 'Khoya', 'ANNADAAN', '260', '7', '1820');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('56', 'Kitchen king 100gm', 'ANNADAAN', '76', '5', '380');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('57', 'Lavang 10gm', 'ANNADAAN', '15', '3', '45');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('58', 'Lemon yellow color 10gm', 'ANNADAAN', '20', '3', '60');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('59', 'Lijjat Papad', 'ANNADAAN', '340', '7', '2380');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('60', 'Magaj Beej', 'ANNADAAN', '720', '3', '2160');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('61', 'Maida', 'ANNADAAN', '40', '15', '600');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('62', 'Matar', 'ANNADAAN', '85', '5', '425');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('63', 'Matchbox', 'ANNADAAN', '10', '1', '10');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('64', 'Milk', 'ANNADAAN', '74', '90', '6660');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('65', 'Mirchi', 'ANNADAAN', '120', '2', '240');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('66', 'Mirchi Powder 200gm', 'ANNADAAN', '110', '5', '550');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('67', 'Mohri (mustard seeds) 100 gm', 'ANNADAAN', '20', '1', '20');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('68', 'Moong dal', 'ANNADAAN', '120', '6', '720');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('69', 'Mushroom', 'ANNADAAN', '120', '3', '360');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('70', 'Napkin', 'ANNADAAN', '15', '12', '180');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('71', 'Nirma', 'ANNADAAN', '60', '10', '600');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('72', 'Onion', 'ANNADAAN', '30', '35', '1050');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('73', 'Onion Masala 200gm', 'ANNADAAN', '110', '8', '880');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('74', 'Paneer', 'ANNADAAN', '240', '20', '4800');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('75', 'Paper napkin', 'ANNADAAN', '40', '14', '560');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('76', 'Pav bhaji masala 100gm', 'ANNADAAN', '75', '4', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('77', 'Pista 100 gm', 'ANNADAAN', '220', '2', '440');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('78', 'Potato', 'ANNADAAN', '30', '12', '360');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('79', 'Pudina bunch', 'ANNADAAN', '20', '8', '160');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('80', 'Rawa Barik', 'ANNADAAN', '45', '3', '135');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('81', 'Red Label 100gm', 'ANNADAAN', '32', '2', '64');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('82', 'Rice Basmati', 'ANNADAAN', '68', '50', '3400');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('83', 'Sabji masala 100gm', 'ANNADAAN', '220', '5', '1100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('84', 'Salt packet', 'ANNADAAN', '29', '8', '232');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('85', 'Salt rock', 'ANNADAAN', '12', '2', '24');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('86', 'Silver foil', 'ANNADAAN', '280', '2', '560');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('87', 'Sooran', 'ANNADAAN', '80', '5', '400');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('88', 'Spinach bunch', 'ANNADAAN', '20', '10', '200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('89', 'Sponge gourd', 'ANNADAAN', '60', '5', '300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('90', 'Steel scrubber', 'ANNADAAN', '10', '4', '40');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('91', 'Sticky Tape', 'ANNADAAN', '30', '5', '150');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('92', 'Sugar', 'ANNADAAN', '44', '65', '2860');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('93', 'Tasting Powder', 'ANNADAAN', '20', '2', '40');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('94', 'Tej patta', 'ANNADAAN', '10', '3', '30');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('95', 'Tomato', 'ANNADAAN', '80', '15', '1200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('96', 'Tomato Ketchup', 'ANNADAAN', '50', '5', '250');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('97', 'Tondli', 'ANNADAAN', '80', '4', '320');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES ('98', 'Toor dal', 'ANNADAAN', '120', '10', '1200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (99, 'Udad dal', 'ANNADAAN', '130', '10', '1300');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (100, '1 Year Maintenance', 'TEMPLE', 1, '1', '150000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (101, 'Aarti thali', 'TEMPLE', 1, '1', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (102, 'Agarbatti stand', 'TEMPLE', 1, '1', '100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (103, 'All Murtis', 'TEMPLE', 1, '1', '70000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (104, 'Asan (mat for sitting)', 'TEMPLE', 1, '1', '500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (105, 'Camphor (kapoor) holder', 'TEMPLE', 1, '1', '100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (106, 'Conch shell (Shankh)', 'TEMPLE', 1, '1', '2000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (107, 'Dhoop stand', 'TEMPLE', 1, '1', '100');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (108, 'Diya (small, big and samai)', 'TEMPLE', 1, '1', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (109, 'Donation box with locks', 'TEMPLE', 1, '1', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (110, 'Door', 'TEMPLE', 1, '1', '100000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (111, 'Fabrication', 'TEMPLE', 1, '1', '10000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (112, 'Fan', 'TEMPLE', 1, '1', '5000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (113, 'Ghanta', 'TEMPLE', 1, '1', '5000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (114, 'Ghanti', 'TEMPLE', 1, '1', '500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (115, 'Granite & Tiles', 'TEMPLE', 1, '1', '300000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (116, 'Hand Bell', 'TEMPLE', 1, '1', '2000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (117, 'Kalash above shiv ji', 'TEMPLE', 1, '1', '2000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (118, 'Lights All', 'TEMPLE', 1, '1', '25000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (119, 'Lock', 'TEMPLE', 1, '1', '200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (120, 'Mahaprasad', 'TEMPLE', 1, '1', '50000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (121, 'Main Kalash', 'TEMPLE', 1, '1', '12000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (122, 'Mandir stapana puja', 'TEMPLE', 1, '1', '100000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (123, 'Nag', 'TEMPLE', 1, '1', '2000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (124, 'Paint', 'TEMPLE', 1, '1', '30000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (125, 'Panchpatra & Achamani', 'TEMPLE', 1, '1', '500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (126, 'Pooja Lotta (big and small)', 'TEMPLE', 1, '1', '500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (127, 'Pooja thali 2pcs', 'TEMPLE', 1, '1', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (128, 'Prasad bowl (medium size)', 'TEMPLE', 1, '1', '200');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (129, 'Samai Pair', 'TEMPLE', 1, '1', '1500');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (130, 'Tal Manjira (medium size)', 'TEMPLE', 1, '1', '1000');
INSERT INTO items (id, item_name, type, price, quantity, amount) VALUES (131, 'Trisul with Damru', 'TEMPLE', 1, '1', '2000');